name: Auto Approve
on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          echo "Viewing Files"
          FILES=$(gh pr view -json files | jq '[.files[].path]' -r -c)
          echo $FILES
      - uses: hmarr/auto-approve-action@v4
        if: startsWith(github.event.pull_request.title, 'Auto PR for')